# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #Instalar as dependencias
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn
        
        # Executar a buid
      - name: Build
        run: yarn build
        
        
#Copiar a pasta dist para dentro da DigitalOcean
      
      - name: Copy dist to DGO
        uses: appleboy/scp-action@master
        with:
          host:${{secrets.SSH_HOST}}
          username:${{secrets.SSH_USER}}
          port:${{secrets.SSH_PORT}}
          key:${{secrets.SSH_KEY}}
          source:"dist"
          target:"test"
   
      



#Copiar a pasta dist para dentro da DigitalOcean


#Subistituir o codigo da pasta dist pelo novo codigo
# Entrar na DG e Instalar as dependencias 'yarn'
#Executar as migrations do typeORM
#Restarto o node Sevrer
